export * from './Banner'
export * from './CardInBanner'
export * from './CardInSolutions'
export * from './Footer'
export * from './Header'
export * from './OurStore'
export * from './Search'
// export * from './footer'